# Generated by Django 3.2.13 on 2022-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, max_length=400)),
                ('rating', models.IntegerField()),
                ('watched', models.BooleanField(default=False)),
                ('imdb_link', models.URLField()),
            ],
        ),
    ]
