# Generated by Django 3.2.13 on 2022-06-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='summary',
            new_name='description',
        ),
    ]
